services:
  grafana:
    container_name: grafana_dev
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage-dev:/var/lib/grafana

  prometheus:
    container_name: prometheus_dev
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus_dev.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage-dev:/prometheus

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=host.docker.internal:6379

  loki:
    image: grafana/loki:2.9.0
    container_name: loki_dev
    ports:
      - "3101:3101"
    volumes:
      - ./loki/loki_dev.yaml:/etc/loki/local-config.yaml
      - loki-storage-dev:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

volumes:
  grafana-storage-dev:
    name: monitoring_grafana-storage-dev
  prometheus-storage-dev:
    name: monitoring_prometheus-storage-dev
  loki-storage-dev:
    name: monitoring_loki-storage-dev
