name: server DEV CI/CD

on:
  push:
    branches:
      - 'develop'

jobs:
  build-docker-image:
    runs-on: macmini # 로컬 Mac mini에서 실행되도록 설정
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드 수행: profile 지정 (우선 테스트 무시하고 빌드)
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test
        env:
          SPRING_PROFILES_ACTIVE: dev


      - name: Build Docker image
        run: |
          docker build -t macmini/team6_server_dev:latest .

  deploy:
    needs: build-docker-image
    runs-on: [macmini]
    steps:

      - name: Stop existing Docker container (if running)
        run: |
          docker kill team6_server_dev || true
          docker rm team6_server_dev || true

      - name: Run new Docker container
        run: |
          docker run --rm -it -d -p 8081:8080 \
          --name team6_server_dev \
          -e SPRING_PROFILES_ACTIVE=dev \
          -v /Users/scienceyds/team6/application-dev.properties:/app/application-dev.properties \
          macmini/team6_server_dev:latest

