name: Monitoring PROD CI/CD

on:
  push:
    branches:
      - monitoring

jobs:
  deploy-monitoring-prod:
    runs-on: macmini

    steps:
      - uses: actions/checkout@v4

      - name: Deploy PROD monitoring stack
        working-directory: monitoring
        env:
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
          GF_SERVER_ROOT_URL: ${{ secrets.PROD_BASE_URL }}${{ secrets.GF_ROUTE_PREFIX }}
          PROM_ROUTE_PREFIX: ${{ secrets.PROM_ROUTE_PREFIX }}
          PROM_WEB_EXTERNAL_URL: ${{ secrets.PROD_BASE_URL }}${{ secrets.PROM_ROUTE_PREFIX }}
        run: |
          # 이전에 실행 중인 prod 컨테이너만 중지
          docker compose -p monitoring_prod -f docker-compose.base.yml -f docker-compose.prod.yml down || true
          # prod 환경 컨테이너 시작
          docker compose -p monitoring_prod -f docker-compose.base.yml -f docker-compose.prod.yml up -d
